"use client";

import { useState } from "react";
import {
  Download,
  FileSpreadsheet,
  FileText,
  RefreshCw,
  ShieldCheck,
} from "lucide-react";

const initialReports = [
  {
    id: "BI-RPT-1",
    name: "Executive ERP Performance",
    owner: "Analytics CoE",
    period: "June 2026",
    status: "Ready",
    type: "Board Pack",
    pages: 18,
  },
  {
    id: "BI-RPT-2",
    name: "Cross Module Variance",
    owner: "Finance BI",
    period: "June 2026",
    status: "Ready",
    type: "Variance Analysis",
    pages: 12,
  },
  {
    id: "BI-RPT-3",
    name: "Workforce and Payroll Insights",
    owner: "HR Analytics",
    period: "June 2026",
    status: "Draft",
    type: "Operational Review",
    pages: 9,
  },
];

function openPdf(report: (typeof initialReports)[number]) {
  const html = `
    <html>
      <head>
        <title>${report.name}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; color: #111827; background: #f8fafc; }
          .page { width: 900px; margin: 32px auto; background: white; padding: 44px; border: 1px solid #dbe3ef; }
          .top { display: flex; justify-content: space-between; border-bottom: 5px solid #7c3aed; padding-bottom: 18px; }
          h1 { margin: 0; font-size: 30px; color: #0f172a; }
          .meta { color: #64748b; margin-top: 8px; }
          .badge { background: #dcfce7; color: #166534; padding: 7px 12px; border-radius: 999px; font-weight: 700; }
          .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin-top: 28px; }
          .card { border: 1px solid #dbe3ef; padding: 16px; background: #f8fafc; }
          .card strong { display: block; font-size: 22px; margin-top: 8px; }
          table { width: 100%; border-collapse: collapse; margin-top: 28px; }
          th { background: #111827; color: white; text-align: left; padding: 12px; }
          td { border: 1px solid #cbd5e1; padding: 12px; }
          .section { margin-top: 28px; border: 1px solid #dbe3ef; padding: 18px; }
          .footer { margin-top: 32px; font-size: 12px; color: #64748b; display: flex; justify-content: space-between; }
        </style>
      </head>
      <body>
        <main class="page">
          <div class="top">
            <div>
              <h1>${report.name}</h1>
              <div class="meta">Infinity Cloud ERP | ${report.type} | ${report.period}</div>
            </div>
            <span class="badge">${report.status}</span>
          </div>
          <div class="grid">
            <div class="card">Revenue<strong>$48.2M</strong><span>+12.4%</span></div>
            <div class="card">Margin<strong>28.6%</strong><span>+2.1%</span></div>
            <div class="card">Automation<strong>82%</strong><span>AI confidence</span></div>
            <div class="card">Risk<strong>Low</strong><span>Enterprise posture</span></div>
          </div>
          <div class="section">
            <h2>Executive Summary</h2>
            <p>This report consolidates performance signals from Finance, HR, Payroll, SCM, Forecasting, Projects, Audit, and Notifications into a board-ready operating view.</p>
          </div>
          <table>
            <thead>
              <tr><th>Domain</th><th>KPI</th><th>Current</th><th>Trend</th><th>Management Action</th></tr>
            </thead>
            <tbody>
              <tr><td>Finance</td><td>Revenue close</td><td>$48.2M</td><td>+12.4%</td><td>Monitor APAC margin variance</td></tr>
              <tr><td>HR</td><td>Workforce utilization</td><td>86%</td><td>+3.8%</td><td>Rebalance project staffing</td></tr>
              <tr><td>SCM</td><td>Inventory health</td><td>94%</td><td>+4.0%</td><td>Approve reorder recommendations</td></tr>
              <tr><td>Projects</td><td>Delivery progress</td><td>75%</td><td>Stable</td><td>Escalate high-risk integration workstream</td></tr>
            </tbody>
          </table>
          <div class="footer">
            <span>Generated by Analytics CoE</span>
            <span>Confidential - Northstar Manufacturing</span>
          </div>
        </main>
      </body>
    </html>
  `;
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
}

function exportCsv(report: (typeof initialReports)[number]) {
  const rows = [
    ["Report", "Owner", "Period", "Domain", "KPI", "Current", "Trend", "Action"],
    [report.name, report.owner, report.period, "Finance", "Revenue close", "$48.2M", "+12.4%", "Monitor APAC margin variance"],
    [report.name, report.owner, report.period, "HR", "Workforce utilization", "86%", "+3.8%", "Rebalance project staffing"],
    [report.name, report.owner, report.period, "SCM", "Inventory health", "94%", "+4.0%", "Approve reorder recommendations"],
    [report.name, report.owner, report.period, "Projects", "Delivery progress", "75%", "Stable", "Escalate integration risk"],
  ];
  const csv = rows.map((row) => row.map((cell) => `"${cell}"`).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${report.name.replace(/\s+/g, "-").toLowerCase()}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

export default function AnalyticsReportsPage() {
  const [reports, setReports] = useState(initialReports);

  function refreshReports() {
    setReports((current) =>
      current.map((report) => ({
        ...report,
        status:
          report.status === "Ready"
            ? "Updated"
            : "Ready",
      }))
    );
  }

  function addReport() {
    const nextId = reports.length + 1;

    const reportTypes = [
      "Board Pack",
      "Variance Analysis",
      "Operational Review",
    ];

    const randomType =
      reportTypes[
      Math.floor(
        Math.random() * reportTypes.length
      )
      ];

    setReports((current) => [
      ...current,
      {
        id: `BI-RPT-${nextId}`,
        name: `${randomType} Report`,
        owner: "Analytics Team",
        period: "June 2026",
        status: "Ready",
        type: randomType,
        pages: Math.floor(Math.random() * 20) + 5,
      },
    ]);
  }
  return (
    <div className="space-y-8">
      <section className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-4xl font-semibold tracking-tight text-white">Analytics reports</h1>
          <p className="mt-3 max-w-3xl text-lg text-slate-300">
            Board-ready BI reports with cross-module KPIs, executive summaries, and export-ready detail tables.
          </p>
        </div>
        <button
          onClick={refreshReports}
          className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-5 py-3 font-semibold text-white">
          <RefreshCw className="h-5 w-5" />
          Refresh reports
        </button>
        <button
          onClick={addReport}
          className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"
        >
          <Download className="h-5 w-5" />
          Add Report
        </button>
      </section>

      <section className="grid gap-4 md:grid-cols-4">
        {[
          [
            "Published Reports",
            reports.length,
            "Available",
          ],
          [
            "Ready Reports",
            reports.filter(
              (r) => r.status === "Ready"
            ).length,
            "Production Ready",
          ],
          [
            "Updated Reports",
            reports.filter(
              (r) => r.status === "Updated"
            ).length,
            "Recently Refreshed",
          ],
          [
            "Data Domains",
            "8",
            "Finance to Audit",
          ],
        ].map(([label, value, note]) => (
          <div key={label} className="rounded-2xl border border-white/10 bg-white/[0.04] p-6">
            <p className="text-sm text-slate-300">{label}</p>
            <p className="mt-3 text-3xl font-semibold text-white">{value}</p>
            <p className="mt-2 text-cyan-300">{note}</p>
          </div>
        ))}
      </section>

      <section className="rounded-2xl border border-white/10 bg-white/[0.04] p-6">
        <h2 className="text-2xl font-semibold text-white">Report library</h2>
        <p className="mt-1 text-slate-300">Certified analytics packs for executive review and operating cadence.</p>

        <div className="mt-8 overflow-x-auto">
          <table className="min-w-full text-left">
            <thead className="text-sm uppercase tracking-[0.28em] text-cyan-300">
              <tr>
                <th className="px-4 py-3">Report</th>
                <th className="px-4 py-3">Type</th>
                <th className="px-4 py-3">Period</th>
                <th className="px-4 py-3">Owner</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/10">
              {reports.map((report) => (
                <tr key={report.id} className="text-slate-100">
                  <td className="px-4 py-5">
                    <div className="font-semibold">{report.name}</div>
                    <div className="text-sm text-slate-400">{report.pages} pages</div>
                  </td>
                  <td className="px-4 py-5">{report.type}</td>
                  <td className="px-4 py-5">{report.period}</td>
                  <td className="px-4 py-5">{report.owner}</td>
                  <td className="px-4 py-5">
                    <span className="inline-flex items-center gap-2 rounded-full bg-emerald-400/10 px-3 py-1 text-sm font-semibold text-emerald-200">
                      <ShieldCheck className="h-4 w-4" />
                      {report.status}
                    </span>
                  </td>
                  <td className="px-4 py-5">
                    <div className="flex flex-wrap gap-2">
                      <button
                        onClick={() => openPdf(report)}
                        className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-violet-500 to-pink-500 px-4 py-2 font-semibold text-white"
                      >
                        <FileText className="h-4 w-4" />
                        PDF
                      </button>
                      <button
                        onClick={() => exportCsv(report)}
                        className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[0.03] px-4 py-2 font-semibold text-white"
                      >
                        <FileSpreadsheet className="h-4 w-4" />
                        Excel
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
