"use client";

import { jsPDF } from "jspdf";
import {
  CheckCircle2,
  Truck,
  Trash2,
  FileDown,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import { ScmStatusBadge } from "@/components/scm/ScmStatusBadge";
import { ScmTable } from "@/components/scm/ScmTable";
import { useScmStore } from "@/store/scm-store";

export default function StockTransfersPage() {
  const {
    stockTransfers,
    warehouses,
    dispatchTransfer,
    completeTransfer,
    deleteTransfer,
  } = useScmStore();

  const downloadReport = (
    transfer: (typeof stockTransfers)[number]
  ) => {
    const sourceWarehouse =
      warehouses.find(
        (warehouse) =>
          warehouse.name ===
          transfer.fromWarehouse
      );

    const destinationWarehouse =
      warehouses.find(
        (warehouse) =>
          warehouse.name ===
          transfer.toWarehouse
      );

    const pdf = new jsPDF();

    let y = 20;

    pdf.setFontSize(18);
    pdf.text(
      "CLOUD ERP",
      20,
      y
    );

    y += 10;

    pdf.setFontSize(15);
    pdf.text(
      "STOCK TRANSFER REPORT",
      20,
      y
    );

    y += 15;

    pdf.setFontSize(12);

    pdf.text(
      "Transfer Information",
      20,
      y
    );

    y += 8;

    pdf.text(
      `Transfer Number : ${transfer.id}`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Transfer Status : ${transfer.status}`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Transfer Date : ${new Date().toLocaleDateString()}`,
      20,
      y
    );

    y += 8;

    pdf.text(
      "Created By : SCM Manager",
      20,
      y
    );

    y += 15;

    pdf.text(
      "Product Information",
      20,
      y
    );

    y += 8;

    pdf.text(
      `SKU : ${transfer.sku}`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Quantity : ${transfer.quantity} Units`,
      20,
      y
    );

    y += 15;

    pdf.text(
      "Source Warehouse",
      20,
      y
    );

    y += 8;

    pdf.text(
      `Warehouse : ${transfer.fromWarehouse}`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Capacity : ${
        sourceWarehouse?.capacity ?? 0
      } Units`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Utilization : ${
        sourceWarehouse?.utilization ?? 0
      }%`,
      20,
      y
    );

    y += 15;

    pdf.text(
      "Destination Warehouse",
      20,
      y
    );

    y += 8;

    pdf.text(
      `Warehouse : ${transfer.toWarehouse}`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Capacity : ${
        destinationWarehouse?.capacity ?? 0
      } Units`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Utilization : ${
        destinationWarehouse?.utilization ?? 0
      }%`,
      20,
      y
    );

    y += 15;

    pdf.text(
      "Movement Details",
      20,
      y
    );

    y += 8;

    pdf.text(
      `Route : ${transfer.fromWarehouse} → ${transfer.toWarehouse}`,
      20,
      y
    );

    y += 8;

    pdf.text(
      `Current Status : ${transfer.status}`,
      20,
      y
    );

    y += 15;

    pdf.text(
      "Audit Information",
      20,
      y
    );

    y += 8;

    pdf.text(
      "Performed By : SCM Manager",
      20,
      y
    );

    y += 8;

    pdf.text(
      `Audit Timestamp : ${new Date().toLocaleString()}`,
      20,
      y
    );

    y += 15;

    pdf.text(
      "Generated Information",
      20,
      y
    );

    y += 8;

    pdf.text(
      "Generated By : Cloud ERP SCM Module",
      20,
      y
    );

    y += 8;

    pdf.text(
      `Generated At : ${new Date().toLocaleString()}`,
      20,
      y
    );

    pdf.save(
      `${transfer.id}-stock-transfer-report.pdf`
    );
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-semibold">
          Stock Transfers
        </h2>

        <p className="text-sm text-slate-500">
          Inter-warehouse transfer tracking.
        </p>
      </div>

      <ScmTable
        title="Transfers"
        description="Stock movement across warehouses."
        headers={[
          "Transfer",
          "SKU",
          "From",
          "To",
          "Qty",
          "Status",
          "Actions",
        ]}
        rows={stockTransfers.map(
          (transfer) => [
            transfer.id,
            transfer.sku,
            transfer.fromWarehouse,
            transfer.toWarehouse,
            transfer.quantity,

            <ScmStatusBadge
              key={`${transfer.id}-status`}
              status={transfer.status}
            />,

            <div
              key={`${transfer.id}-actions`}
              className="flex items-center justify-center gap-2"
            >
              {transfer.status ===
                "scheduled" && (
                <>
                  <Button
                    size="sm"
                    onClick={() =>
                      dispatchTransfer(
                        transfer.id
                      )
                    }
                  >
                    <Truck className="mr-1 h-4 w-4" />
                    Dispatch
                  </Button>

                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() =>
                      deleteTransfer(
                        transfer.id
                      )
                    }
                  >
                    <Trash2 className="mr-1 h-4 w-4" />
                    Delete
                  </Button>
                </>
              )}

              {transfer.status ===
                "in_transit" && (
                <Button
                  size="sm"
                  onClick={() =>
                    completeTransfer(
                      transfer.id
                    )
                  }
                >
                  <CheckCircle2 className="mr-1 h-4 w-4" />
                  Complete
                </Button>
              )}

              <Button
                size="sm"
                variant="outline"
                onClick={() =>
                  downloadReport(
                    transfer
                  )
                }
              >
                <FileDown className="mr-1 h-4 w-4" />
                Report
              </Button>
            </div>,
          ]
        )}
      />
    </div>
  );
}